# Generated by Django 5.1.7 on 2025-04-05 10:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_recipe_tags_ingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.utils.recipe_image_file_path
            ),
        ),
    ]
