# Generated by Django 5.1.7 on 2025-04-07 12:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.post_content_file_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="content_files",
        ),
        migrations.AddField(
            model_name="post",
            name="content_files",
            field=models.ManyToManyField(blank=True, to="core.postfile"),
        ),
    ]
